// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjppwow4vLGYs-5rFctyKeElvCBy_lOOQ',
    appId: '1:437595422951:web:e411aaa285ef09a3ece242',
    messagingSenderId: '437595422951',
    projectId: 'group-1-36c82',
    authDomain: 'group-1-36c82.firebaseapp.com',
    storageBucket: 'group-1-36c82.appspot.com',
    measurementId: 'G-62TGYKF6KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhuNVR_UoKlrxN3ivUxUX4wh4NgSLcyR0',
    appId: '1:437595422951:android:e05eeb7cc2c991f8ece242',
    messagingSenderId: '437595422951',
    projectId: 'group-1-36c82',
    storageBucket: 'group-1-36c82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLVWV_E2CwuHijWA7GH3gxoxvm9Nap5U',
    appId: '1:437595422951:ios:63d51483bc174c23ece242',
    messagingSenderId: '437595422951',
    projectId: 'group-1-36c82',
    storageBucket: 'group-1-36c82.appspot.com',
    iosBundleId: 'com.example.group1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgLVWV_E2CwuHijWA7GH3gxoxvm9Nap5U',
    appId: '1:437595422951:ios:861e39619596d9deece242',
    messagingSenderId: '437595422951',
    projectId: 'group-1-36c82',
    storageBucket: 'group-1-36c82.appspot.com',
    iosBundleId: 'com.example.group1.RunnerTests',
  );
}
